### PR TITLE
fix(store): resolveUserTypes for static arrays

### LINKED ISSUE #1875: deploy breaks for static-length arrays

### PR DESCRIPTION
**Pull request by dk1a**
fixes #1875

### CODE REVIEW

File: packages/store/ts/config/storeConfig.ts [hunk 1]
```diff
@@ -88,7 +88,18 @@ export function resolveUserTypes<
...
+
+    if (userTypes[value] !== undefined) {
+      // user-defined types
+      resolvedSchema[key] = userTypes[value].internalType as SchemaAbiType;
+    } else if (staticArray) {
+      // static arrays
+      resolvedSchema[key] = `${staticArray.elementType as StaticAbiType}[]`;
+    } else {
+      // abi types
+      resolvedSchema[key] = value as SchemaAbiType;
```
Comment (holic) [inline packages/store/ts/config/storeConfig.ts:101]: we have a type-narrowing `isSchemaAbiType` that could help here

may also be slightly faster to put this as the first check and only parse the array if we don't have a schema ABI type or user type

File: packages/store/ts/config/storeConfig.ts [hunk 2]
```diff
@@ -88,7 +88,18 @@ export function resolveUserTypes<
...
+    }
```
Comment (holic) [inline packages/store/ts/config/storeConfig.ts:102]:
```suggestion
    const staticArray = parseStaticArray(value);

    if (isSchemaAbiType(value)) {
      resolvedSchema[key] = value;
    else if (userTypes[value] !== undefined) {
      resolvedSchema[key] = userTypes[value].internalType as SchemaAbiType;
    } else {
      const staticArray = parseStaticArray(value);
      if (!staticArray) throw new Error(`Unexpected type: ${value}`);
      resolvedSchema[key] = `${staticArray.elementType as StaticAbiType}[]`;
    }
```

File: e2e/packages/contracts/mud.config.ts [hunk 3]
```diff
@@ -47,5 +47,9 @@ export default mudConfig({
         player: "address",
       },
     },
+    StaticArray: {
+      keySchema: {},
+      valueSchema: "uint256[2]",
+    },
```
Comment (holic) [inline e2e/packages/contracts/mud.config.ts:53]: do we have or want tests for this? or are e2e tests just being compiled/run enough?

**Review by holic — DISMISSED** [review]
just a small nit around logic and type narrowing but otherwise lgtm!

File: packages/store/ts/config/storeConfig.ts (hunk 2 above)
Comment (holic) [reply packages/store/ts/config/storeConfig.ts:102]: oh actually, I think this file deals with old schema ABI type abstractions, so that may not work

File: e2e/packages/contracts/mud.config.ts (hunk 3 above)
Comment (dk1a) [reply e2e/packages/contracts/mud.config.ts:53]: the table being deployed is enough, which happens in just e2e tests being run

File: packages/store/ts/config/storeConfig.ts (hunk 2 above)
Comment (dk1a) [reply packages/store/ts/config/storeConfig.ts]: added `isSchemaAbiType` and imported and used the suggestion

**Review by holic — DISMISSED** [review]

**Review by holic — APPROVED** [review]
