### PR TITLE
fix(common): fix memory corruption for dynamic to static array conversion

### LINKED ISSUE #1005: Possible array to static array memory corruption
Reminder to self to investigate a potential memory corruption issue during the cast of an **uninitialized** dynamic array to a static array within autogenerated tables

### PR DESCRIPTION
**Pull request by dk1a**
fixes #1005

### CODE REVIEW

File: packages/common/src/codegen/render-solidity/renderTypeHelpers.ts [hunk 1]
```diff
@@ -63,9 +63,15 @@ function renderWrapperStaticArray(
...
-        _result := add(_value, 0x20)
+      if (_value.length < ${staticLength}) {
+        // ignore invalid dynamic arrays that are too small
+        return _result;
+      } else {
+        // in memory static arrays are just dynamic arrays without the length byte
+        // (without the length check this could lead to memory corruption)
+        assembly {
+          _result := add(_value, 0x20)
+        }
```
Comment (holic) [inline packages/common/src/codegen/render-solidity/renderTypeHelpers.ts:74]: any way we can add a regression test for this to make sure we don't run into this in the future?

File: packages/cli/contracts/src/codegen/tables/Dynamics1.sol [hunk 2]
```diff
@@ -1495,37 +1495,67 @@ library Dynamics1 {
 }
 
 function toStaticArray_bytes32_1(bytes32[] memory _value) pure returns (bytes32[1] memory _result) {
-  // in memory static arrays are just dynamic arrays without the length byte
-  assembly {
-    _result := add(_value, 0x20)
+  if (_value.length < 1) {
+    // ignore invalid dynamic arrays that are too small
+    return _result;
```
Comment (holic) [inline packages/cli/contracts/src/codegen/tables/Dynamics1.sol:1500]: if this is invalid, should this revert instead of returning?

Comment (dk1a) [reply packages/cli/contracts/src/codegen/tables/Dynamics1.sol:1500]: a 0-length array is kinda valid (it's uninitialized), so maybe I should change the comment?
and other cases are weird and shouldn't happen, but it's cheaper to return empty than add more checks

File: packages/common/src/codegen/render-solidity/renderTypeHelpers.ts (hunk 1 above)
Comment (dk1a) [reply packages/common/src/codegen/render-solidity/renderTypeHelpers.ts:74]: memory corruption tests are tricky, I think I'm too sleepy to write 1 rn, we can add an issue for later, tests aren't production code so does freeze affect em?

Comment (alvrs) [reply packages/common/src/codegen/render-solidity/renderTypeHelpers.ts:74]: we can always add more tests later! planning to do extend the test suite in general next week

File: packages/common/src/codegen/render-solidity/renderTypeHelpers.ts [hunk 3]
```diff
@@ -63,9 +63,15 @@ function renderWrapperStaticArray(
     ) pure returns (
       ${elementType}[${staticLength}] memory _result
     ) {
-      // in memory static arrays are just dynamic arrays without the length byte
-      assembly {
-        _result := add(_value, 0x20)
+      if (_value.length < ${staticLength}) {
+        // ignore invalid dynamic arrays that are too small
```
Comment (alvrs) [inline packages/common/src/codegen/render-solidity/renderTypeHelpers.ts:67]:
```suggestion
        // return an uninitialized array if the length is smaller than the fixed length to avoid memory corruption
```

File: packages/common/src/codegen/render-solidity/renderTypeHelpers.ts (hunk 1 above)
Comment (holic) [reply packages/common/src/codegen/render-solidity/renderTypeHelpers.ts:74]: added here: https://github.com/latticexyz/mud/issues/1603
