### PR TITLE
fix(gas-report): update filename matcher

### LINKED ISSUE #2276: Gas report fails to find test filename
```
[...]
Done reading stdin
Error: Could not find nearest test filename, did `forge test` output change?
````

Output of `forge test` did in fact change in latest version.

Running:
```
forge 0.2.0 (c631cf3 2024-02-18T00:17:43.475108000Z)
```

### PR DESCRIPTION
**Pull request by pwrstudio**
Fixes #2276

### CODE REVIEW

File: packages/gas-report/ts/index.ts [hunk 1]
```diff
@@ -130,7 +130,7 @@ async function runGasReport(options: Options): Promise<GasReport> {
   const lines = logs.split("\n").map(stripAnsi);
   const gasReportPattern = /^\s*GAS REPORT: (\d+) (.*)$/;
   const testFunctionPattern = /^\[(?:PASS|FAIL).*\] (\w+)\(\)/;
-  const testFilePattern = /^Running \d+ tests? for (.*):(.*)$/;
+  const testFilePattern = /^Ran \d+ tests? for (.*):(.*)$/;
```
Comment (holic) [inline packages/gas-report/ts/index.ts:133]: nice catch! thoughts on testing for both instead of just one? so we can support older foundry versions for a little while? maybe with a comment explaining

Comment (pwrstudio) [reply packages/gas-report/ts/index.ts]: Sure! I have amended the commit.

**Comment by holic** [comment]
can you enable us to edit the branch/PR? I'd like to add a changeset so we can merge this

**Comment by holic** [comment]
that's okay! another option is to add the changeset yourself

```
pnpm run changeset
```

from the root of the mud repo

File: .changeset/purple-cooks-remember.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+"@latticexyz/gas-report": patch
+---
+
+fix: gas report fails to find test filename
```
Comment (holic) [inline .changeset/purple-cooks-remember.md:5]:
```suggestion
Fixed gas report parsing for foundry versions released after 2024-02-15.
```

**Review by holic — APPROVED** [review]

**Comment by holic** [comment]
thank you!
