### PR TITLE
fix(cli): throw warning for duplicate systems

### LINKED ISSUE #2263: Throw warning when systems have same prefixes
When two system names have identical prefixes up to index 16, there is an occasional bug in the deploy script where one of the systems doesn't register properly to the world. The revert thrown when calling the system excludes a message and the bug occurs at different rates depending on the environment (20-50%).

### PR DESCRIPTION
**Pull request by vmaark**
Resolves #2263 

Throw error when systems with the same ids occur.

### CODE REVIEW

File: packages/cli/src/deploy/resolveConfig.ts [hunk 1]
```diff
@@ -79,6 +79,12 @@ export function resolveConfig<config extends ConfigInput>({
     };
   });
 
+  systems.forEach((item, index) => {
+    if (systems.some((elem, idx) => elem.systemId === item.systemId && idx !== index)) {
+      throw new Error(`Duplicate system ID ${item.systemId} found in the config.`);
+    }
+  });
```
Comment (holic) [inline packages/cli/src/deploy/resolveConfig.ts:86]: Since we are working with objects, we could probably simplify this a bit by just checking if each `item` and `elem` are not the same (rather than their indices).

I think we could improve this error message too, to something like:

> Found two systems with the same system ID: {name1}, {name2}
>
> System IDs are generated from the first 14 bytes of the name, so you may need to rename one of these systems to avoid the overlap.

**Comment by holic** [comment]
Looks like there's a merge conflict, which is keeping CI from running.

File: packages/cli/src/deploy/resolveConfig.ts (hunk 1 above)
Comment (vmaark) [reply packages/cli/src/deploy/resolveConfig.ts:89]: improved the error message. 
I think it's safer to use the idx in the context of objects, a change in the logic could easily introduce a bug where you'd be checking e.q. the equality of different objects but with the same id (and they would never equal on the object reference level)

Comment (holic) [reply packages/cli/src/deploy/resolveConfig.ts:89]: in this case, we're just trying to make sure we're comparing system IDs, but we don't want to compare to itself, so an object reference

Comment (holic) [reply packages/cli/src/deploy/resolveConfig.ts:89]: re: above code, could potentially clarify with

```
const overlappingSystem = systems.find(...);
if (overlappingSystem) {
  throw new Error(`Found two systems with the same system ID: ${system.name} ${overlappingSystem.name}.\n\nSystem IDs are generated from the first 14 bytes of the name, so you may need to rename one of these systems to avoid the overlap.`);
}
```
